// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function DeveloperDiagnosticsEnabled() {
  return window['go']['main']['App']['DeveloperDiagnosticsEnabled']();
}

export function ExportDiagnosticHistory() {
  return window['go']['main']['App']['ExportDiagnosticHistory']();
}

export function GetAutomaticCaptureStatus() {
  return window['go']['main']['App']['GetAutomaticCaptureStatus']();
}

export function GetCaptureSession() {
  return window['go']['main']['App']['GetCaptureSession']();
}

export function GetDownloadTechnicalContext(arg1) {
  return window['go']['main']['App']['GetDownloadTechnicalContext'](arg1);
}

export function GetTechnicalContext(arg1) {
  return window['go']['main']['App']['GetTechnicalContext'](arg1);
}

export function ListCapturedStreams() {
  return window['go']['main']['App']['ListCapturedStreams']();
}

export function ListDiagnosticHistory() {
  return window['go']['main']['App']['ListDiagnosticHistory']();
}

export function ListDownloadJobs() {
  return window['go']['main']['App']['ListDownloadJobs']();
}

export function QueueCapturedStream(arg1) {
  return window['go']['main']['App']['QueueCapturedStream'](arg1);
}

export function QueueDownload(arg1) {
  return window['go']['main']['App']['QueueDownload'](arg1);
}

export function RepairAutomaticCapture() {
  return window['go']['main']['App']['RepairAutomaticCapture']();
}

export function SetCaptureDiagnostic(arg1) {
  return window['go']['main']['App']['SetCaptureDiagnostic'](arg1);
}

export function SetDeveloperDiagnostics(arg1) {
  return window['go']['main']['App']['SetDeveloperDiagnostics'](arg1);
}

export function StartFirefoxCapture() {
  return window['go']['main']['App']['StartFirefoxCapture']();
}

export function StartManualCapture() {
  return window['go']['main']['App']['StartManualCapture']();
}

export function StopBrowserCapture() {
  return window['go']['main']['App']['StopBrowserCapture']();
}

export function StopFirefoxCapture() {
  return window['go']['main']['App']['StopFirefoxCapture']();
}
