// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ListCapturedStreams() {
  return window['go']['main']['App']['ListCapturedStreams']();
}

export function ListDownloadJobs() {
  return window['go']['main']['App']['ListDownloadJobs']();
}

export function QueueCapturedStream(arg1) {
  return window['go']['main']['App']['QueueCapturedStream'](arg1);
}

export function QueueDownload(arg1) {
  return window['go']['main']['App']['QueueDownload'](arg1);
}

export function StartFirefoxCapture() {
  return window['go']['main']['App']['StartFirefoxCapture']();
}

export function StopFirefoxCapture() {
  return window['go']['main']['App']['StopFirefoxCapture']();
}
