// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';
import {capture} from '../models';
import {diagnostics} from '../models';
import {main} from '../models';

export function CancelDownload(arg1:string):Promise<download.JobSnapshot>;

export function DeveloperDiagnosticsEnabled():Promise<boolean>;

export function ExportDiagnosticHistory():Promise<string>;

export function GetCaptureSession():Promise<capture.SessionSnapshot>;

export function ListCapturedStreams():Promise<Array<capture.StreamSummary>>;

export function ListDiagnosticHistory():Promise<Array<diagnostics.Diagnostic>>;

export function ListDownloadJobs():Promise<Array<download.JobSnapshot>>;

export function QueueCapturedStream(arg1:main.CapturedDownloadRequest):Promise<download.JobSnapshot>;

export function QueueDownload(arg1:main.DownloadRequest):Promise<download.JobSnapshot>;

export function SetCaptureDiagnostic(arg1:diagnostics.Diagnostic):Promise<void>;

export function SetDeveloperDiagnostics(arg1:boolean):Promise<void>;

export function StartFirefoxCapture():Promise<capture.Pairing>;

export function StopBrowserCapture():Promise<void>;

export function StopFirefoxCapture():Promise<void>;
