// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadCapturedStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListCapturedStreams():Promise<Array<capture.Stream>>;

export function QueueCapturedStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function QueueDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartFirefoxCapture():Promise<capture.Pairing>;

export function StopFirefoxCapture():Promise<void>;
