// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function DownloadCapturedStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadCapturedStream'](arg1, arg2, arg3);
}

export function ListCapturedStreams() {
  return window['go']['main']['App']['ListCapturedStreams']();
}

export function StartFirefoxCapture() {
  return window['go']['main']['App']['StartFirefoxCapture']();
}

export function StopFirefoxCapture() {
  return window['go']['main']['App']['StopFirefoxCapture']();
}
